version: '3.6'
services:
  phoenix:
    build: .
    environment:
      MIX_ENV: dev
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
